### PR TITLE
update Bullseye from 2.3.0 to 2.4.0-rc.2

### PR DESCRIPTION
**Pull request by adamralph**
Feature of interest: https://github.com/adamralph/bullseye/issues/168

### CODE REVIEW

**Comment by adamralph** [comment]
Looks like the build failed due to a flaky test.

**Comment by damianh** [comment]
Yeah race condition in that test :/

**Comment by adamralph** [comment]
Kicked off another build, but same again.

**Comment by thefringeninja** [comment]
Hoping #294 will fix it

**Comment by thefringeninja** [comment]
Hey @adamralph can you rebase your PR please and push it up? I think I fixed that particular issue.

**Comment by adamralph** [comment]
@thefringeninja done.

**Comment by adamralph** [comment]
Looks like the same test is still failing 😢

**Comment by adamralph** [comment]
Same thing on the latest master build: https://travis-ci.org/SQLStreamStore/SQLStreamStore/builds/561165153#L1285

**Comment by thefringeninja** [comment]
Nope, that's a different test

**Pull request merged**
