### PR TITLE
update Bullseye, SimpleExec, and MinVer to latest RC

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
Managed to get a green build on the third attempt. Looks like there are still some flaky tests around.

**Comment by damianh** [comment]
Cheers lad.

**Comment by damianh** [comment]
Btw, have dependebot applied, the new packages should be PR'd automagically.

**Comment by adamralph** [comment]
@damianh does it work OK for pre-releases? I can't see that it's ever raised a PR for you for Bullseye, SimpleExec, or MinVer.

**Comment by damianh** [comment]
Hmm, I don't think it does. Noted.

**Pull request merged**
