### PR TITLE
switch publish target to using enumerable inputs

### PR DESCRIPTION
**Pull request by adamralph**
Basically the same deal as in #163.

It just didn't immediately strike me how to do it for the `publish` target.

### CODE REVIEW

**Comment by adamralph** [comment]
Interesting, the build is failing because the artifacts directory doesn't exist at the time the enumeration is made for the publish directory. I'll look into it.

**Comment by adamralph** [comment]
I guess we need a new feature in Bullseye: an overload of `Target` which takes a `Func` for the enumeration?

**Comment by adamralph** [comment]
Closing in favour of #165

**Comment by damianh** [comment]
glad I didn't merge straight away ;)

**Comment by adamralph** [comment]
The build server did its job. 😉

**Pull request closed without merging**
