### PR TITLE
Fix assemblyversion for version 1 releases (minver tweak)

### PR DESCRIPTION
**Pull request by yreynhout**
This PR addresses the issue raised in #377 using the solution proposed by @adamralph

### CODE REVIEW

**Comment by yreynhout** [comment]
Proof from a local run (extracted dll from a nupkg)

image

**Comment by yreynhout** [comment]
Reflective question: how will this affect components already depending on 1.2.0-beta.x? The requested assembly version will be `1.0.0.0` whereas this change will turn that assembly version into `1.2.0.0`. Thoughts, @adamralph @damianh @thefringeninja ?

**Comment by adamralph** [comment]
@yreynhout doesn't the implicit assembly redirecting take care of that now? I.e if it's a higher version it will just take it?

**Comment by yreynhout** [comment]
I'll have a look at this using a local feed to see how it behaves.

**Comment by yreynhout** [comment]
Just tried this with the local build output, i.e. have an app that depends on 1.2.0-beta.8.71 and a lib that depends on 1.1.3 and have the app depend on the lib and use the lib's type which exposes a SqlStreamStore member ... it seems to be working. Going to merge for now, but we probably want some CI feed beta testers before releasing.

**Pull request merged**
